/**
 * Seed tour log data — real group history for AI personalization.
 * Claude uses this to understand the group's experience level, preferred areas,
 * terrain preferences, and typical tour difficulty.
 *
 * Each tour has exactly 2 waypoints: START and PEAK (highest point reached).
 * Coordinates verified via GeoAdmin (api3.geo.admin.ch).
 */

import type { TourLogEntry } from '@/types';

export const SEED_TOURS: TourLogEntry[] = [
  {
    id: 'tour-1487',
    name: 'Pizzo Nero 2903m',
    date: '2025-01-02',
    participants: ['Laura Köcher'],
    route: {
      name: 'Pizzo Nero 2903m',
      waypoints: [
        { lat: 46.4866, lon: 8.4750, label: "All'Acqua", elevation: 1614 },
        { lat: 46.4925, lon: 8.4111, label: 'Pizzo Nero', elevation: 2903 },
      ],
      dangerZones: [],
      totalElevation: 1300,
      distance: 10,
      estimatedTime: '3h 25min',
      difficulty: 'ZS',
      keyInfo: 'Aggressive Westwind; kalt; Pulverreste; Gipfelaufstieg in direktem südexponierten Couloir (40-45°)',
    },
    conditions: 'Aggressive Westwind; kalt; Pulverreste',
    notes: 'Gipfelaufstieg in direktem südexponierten Couloir (40-45°)',
    rating: 4,
    createdAt: new Date('2025-01-02').getTime(),
  },
  {
    id: 'tour-1488',
    name: 'Val Maighels c. 2150m',
    date: '2026-01-11',
    participants: ['J+S Gruppe'],
    route: {
      name: 'Val Maighels c. 2150m',
      waypoints: [
        { lat: 46.6587, lon: 8.6712, label: 'Oberalppass', elevation: 2044 },
        { lat: 46.6062, lon: 8.6919, label: 'Val Maighels', elevation: 2150 },
      ],
      dangerZones: [],
      totalElevation: 350,
      distance: 8,
      estimatedTime: 'variable',
      difficulty: 'L',
      keyInfo: 'J+S Fortbildungskurs; Lawinenkunde',
    },
    conditions: 'Fortbildungskurs Bedingungen',
    notes: 'J+S Fortbildungskurs; Lawinenkunde',
    rating: 3,
    createdAt: new Date('2026-01-11').getTime(),
  },
  {
    id: 'tour-1489',
    name: 'Lauiberg 2057m',
    date: '2026-01-17',
    participants: ['Niclas Genovese'],
    route: {
      name: 'Lauiberg 2057m',
      waypoints: [
        { lat: 47.0222, lon: 8.8481, label: 'Stägli', elevation: 1067 },
        { lat: 47.0148, lon: 8.8618, label: 'Lauiberg', elevation: 2057 },
      ],
      dangerZones: [],
      totalElevation: 1050,
      distance: 9,
      estimatedTime: 'variable',
      difficulty: 'WS+',
      keyInfo: 'Abfahrt via Stägli. Schwerer Pulverschnee; wenig Volk; Gipfelgrat leicht wächtig aber ok',
    },
    conditions: 'Schwerer Pulverschnee; wenig Volk',
    notes: 'Gipfelgrat leicht wächtig aber ok',
    rating: 4,
    createdAt: new Date('2026-01-17').getTime(),
  },
  {
    id: 'tour-1450',
    name: 'Wasserbergfirst 2341m',
    date: '2026-01-25',
    participants: ['Vincent Wirth'],
    route: {
      name: 'Wasserbergfirst 2341m',
      waypoints: [
        { lat: 46.9371, lon: 8.8361, label: 'Schwarzenbach', elevation: 950 },
        { lat: 46.9395, lon: 8.7890, label: 'Wasserbergfirst', elevation: 2341 },
      ],
      dangerZones: [],
      totalElevation: 1400,
      distance: 12,
      estimatedTime: 'variable',
      difficulty: 'S-',
      keyInfo: 'Schneemangel; einsam; Gipfelhang mit vielen Schneeresten; Steigeisen angenehm; Waldpassage unterhalb Waldhüttli recht zugewachsen; pulvrige Abschnitte',
    },
    conditions: 'Schneemangel; einsam',
    notes: 'Steigeisen angenehm; Waldpassage recht zugewachsen; pulvrige Abschnitte; lohnenswert',
    rating: 4,
    createdAt: new Date('2026-01-25').getTime(),
  },
  {
    id: 'tour-1451',
    name: 'Rossstock 2461m - Schnüerstocksattel 1976m',
    date: '2026-02-01',
    participants: ['Solo'],
    route: {
      name: 'Rossstock 2461m - Schnüerstocksattel',
      waypoints: [
        { lat: 46.9276, lon: 8.6868, label: 'Spilau', elevation: 1060 },
        { lat: 46.9172, lon: 8.7078, label: 'Rossstock', elevation: 2461 },
      ],
      dangerZones: [],
      totalElevation: 1000,
      distance: 11,
      estimatedTime: '1h 7min ascent',
      difficulty: 'WS',
      keyInfo: 'Kalt und praktisch windstill; azyklisch und daher wenig Leute auf Tour. Traverse via Schnüerstocksattel to Chäppeliberg.',
    },
    conditions: 'Kalt und praktisch windstill; azyklisch',
    notes: 'Solo tour; wenig Leute',
    rating: 4,
    createdAt: new Date('2026-02-01').getTime(),
  },
  {
    id: 'tour-1452',
    name: 'Stotzigen Firsten 2747m',
    date: '2026-02-07',
    participants: ['Jonas Widmer', 'Lukas Preiswerk', 'Niclas Genovese'],
    route: {
      name: 'Stotzigen Firsten 2747m',
      waypoints: [
        { lat: 46.5983, lon: 8.5031, label: 'Realp', elevation: 1538 },
        { lat: 46.5658, lon: 8.4385, label: 'Stotzigen Firsten', elevation: 2747 },
      ],
      dangerZones: [],
      totalElevation: 1250,
      distance: 10,
      estimatedTime: 'variable',
      difficulty: 'WS',
      keyInfo: 'Abfahrt via Nordhänge. Mittelmässig Volk; Nordabfahrt mit gutem Pulverschnee; nicht direkt vom Gipfel',
    },
    conditions: 'Mittelmässig Volk; Nordabfahrt mit gutem Pulverschnee',
    notes: 'Nordabfahrt mit gutem Pulver; nicht direkt vom Gipfel',
    rating: 5,
    createdAt: new Date('2026-02-07').getTime(),
  },
  {
    id: 'tour-1453',
    name: 'Balmer Grätli c. 2250m',
    date: '2026-02-15',
    participants: ['Jonas Widmer', 'Lukas Preiswerk'],
    route: {
      name: 'Balmer Grätli c. 2250m',
      waypoints: [
        { lat: 46.8630, lon: 8.7699, label: 'Unterschächen', elevation: 1036 },
        { lat: 46.8824, lon: 8.8272, label: 'Balmer Grätli', elevation: 2250 },
      ],
      dangerZones: [],
      totalElevation: 1250,
      distance: 10,
      estimatedTime: 'variable',
      difficulty: 'WS',
      keyInfo: 'Sehr wenig Betrieb vergleichsweise; super Pulverschnee; unten Schneelage knapp',
    },
    conditions: 'Super Pulverschnee; Schneelage unten knapp',
    notes: 'Sehr wenig Betrieb; super Pulver',
    rating: 5,
    createdAt: new Date('2026-02-15').getTime(),
  },
  {
    id: 'tour-1454',
    name: 'Arnialp',
    date: '2026-02-22',
    participants: ['Niclas Genovese', 'Laura Köcher'],
    route: {
      name: 'Arnialp',
      waypoints: [
        { lat: 46.8048, lon: 8.0850, label: 'Arni-Ziflucht', elevation: 1100 },
        { lat: 46.7978, lon: 8.0781, label: 'Richtung Arnitriste', elevation: 1950 },
      ],
      dangerZones: [],
      totalElevation: 850,
      distance: 8,
      estimatedTime: 'variable',
      difficulty: 'WS',
      keyInfo: 'Feuchter Pulverschnee; kein Volk da Lawinenstufe 3+; keine Wummgeräusche; keine spontanen Anrisse oder Fernauslösungen',
    },
    conditions: 'Feuchter Pulverschnee; Lawinenstufe 3+; keine Wummgeräusche',
    notes: 'Kein Volk da Lawinenstufe 3+; keine spontanen Anrisse oder Fernauslösungen',
    rating: 4,
    createdAt: new Date('2026-02-22').getTime(),
  },
];
