/**
 * Seed tour log data — real group history for AI personalization.
 * Claude uses this to understand the group's experience level, preferred areas,
 * terrain preferences, and typical tour difficulty.
 */

import type { TourLogEntry } from '@/types';

export const SEED_TOURS: TourLogEntry[] = [
  {
    id: 'tour-1487',
    name: 'Pizzo Nero 2903m',
    date: '2025-01-02',
    participants: ['Laura Köcher'],
    route: {
      name: 'Pizzo Nero 2903m',
      waypoints: [
        { lat: 46.5459, lon: 8.3908, label: "All'Acqua", elevation: 1614 },
        { lat: 46.5332, lon: 8.3857, label: 'Nufenenpassstrasse', elevation: 2100 },
        { lat: 46.5135, lon: 8.3791, label: 'Pizzo Nero', elevation: 2903 },
      ],
      dangerZones: [],
      totalElevation: 1300,
      distance: 10,
      estimatedTime: '3h 25min',
      difficulty: 'ZS',
      keyInfo: 'Aggressive Westwind; kalt; Pulverreste; Gipfelaufstieg in direktem südexponierten Couloir (40-45°)',
    },
    conditions: 'Aggressive Westwind; kalt; Pulverreste',
    notes: 'Gipfelaufstieg in direktem südexponierten Couloir (40-45°)',
    rating: 4,
    createdAt: new Date('2025-01-02').getTime(),
  },
  {
    id: 'tour-1488',
    name: 'Val Maighels c. 2150m',
    date: '2026-01-11',
    participants: ['J+S Gruppe'],
    route: {
      name: 'Val Maighels c. 2150m',
      waypoints: [
        { lat: 46.6594, lon: 8.6710, label: 'Oberalppass', elevation: 2044 },
        { lat: 46.6490, lon: 8.6580, label: 'Pt. 1831', elevation: 1831 },
        { lat: 46.6350, lon: 8.6430, label: 'Val Maighels', elevation: 2150 },
        { lat: 46.6300, lon: 8.6800, label: 'Tschamut', elevation: 1652 },
      ],
      dangerZones: [],
      totalElevation: 350,
      distance: 8,
      estimatedTime: 'variable',
      difficulty: 'L',
      keyInfo: 'J+S Fortbildungskurs; Lawinenkunde',
    },
    conditions: 'Fortbildungskurs Bedingungen',
    notes: 'J+S Fortbildungskurs; Lawinenkunde',
    rating: 3,
    createdAt: new Date('2026-01-11').getTime(),
  },
  {
    id: 'tour-1489',
    name: 'Lauiberg 2057m',
    date: '2026-01-17',
    participants: ['Niclas Genovese'],
    route: {
      name: 'Lauiberg 2057m',
      waypoints: [
        { lat: 46.9410, lon: 8.5500, label: 'Pt. 1067m', elevation: 1067 },
        { lat: 46.9340, lon: 8.5350, label: 'Normalroute', elevation: 1600 },
        { lat: 46.9280, lon: 8.5200, label: 'Lauiberg Gipfel', elevation: 2057 },
      ],
      dangerZones: [],
      totalElevation: 1050,
      distance: 9,
      estimatedTime: 'variable',
      difficulty: 'WS+',
      keyInfo: 'Abfahrt via Stägli. Schwerer Pulverschnee; wenig Volk; Gipfelgrat leicht wächtig aber ok',
    },
    conditions: 'Schwerer Pulverschnee; wenig Volk',
    notes: 'Gipfelgrat leicht wächtig aber ok',
    rating: 4,
    createdAt: new Date('2026-01-17').getTime(),
  },
  {
    id: 'tour-1450',
    name: 'Wasserbergfirst 2341m',
    date: '2026-01-25',
    participants: ['Vincent Wirth'],
    route: {
      name: 'Wasserbergfirst 2341m',
      waypoints: [
        { lat: 46.8830, lon: 8.6100, label: 'Schwarzenbach', elevation: 950 },
        { lat: 46.8700, lon: 8.6000, label: 'Normalroute', elevation: 1700 },
        { lat: 46.8600, lon: 8.5900, label: 'Wasserbergfirst', elevation: 2341 },
      ],
      dangerZones: [],
      totalElevation: 1400,
      distance: 12,
      estimatedTime: 'variable',
      difficulty: 'S-',
      keyInfo: 'Schneemangel; einsam; Gipfelhang mit vielen Schneeresten; Steigeisen angenehm; Waldpassage unterhalb Waldhüttli recht zugewachsen; pulvrige Abschnitte',
    },
    conditions: 'Schneemangel; einsam',
    notes: 'Steigeisen angenehm; Waldpassage recht zugewachsen; pulvrige Abschnitte; lohnenswert',
    rating: 4,
    createdAt: new Date('2026-01-25').getTime(),
  },
  {
    id: 'tour-1451',
    name: 'Rossstock 2461m - Schnüerstocksattel 1976m',
    date: '2026-02-01',
    participants: ['Solo'],
    route: {
      name: 'Rossstock 2461m - Schnüerstocksattel',
      waypoints: [
        { lat: 46.9200, lon: 8.7300, label: 'LSB Spilau', elevation: 1060 },
        { lat: 46.9100, lon: 8.7200, label: 'Normalroute', elevation: 1800 },
        { lat: 46.9000, lon: 8.7100, label: 'Rossstock', elevation: 2461 },
        { lat: 46.9050, lon: 8.7050, label: 'Schnüerstocksattel', elevation: 1976 },
        { lat: 46.9120, lon: 8.6900, label: 'Chäppeliberg', elevation: 1500 },
      ],
      dangerZones: [],
      totalElevation: 1000,
      distance: 11,
      estimatedTime: '1h 7min ascent',
      difficulty: 'WS',
      keyInfo: 'Kalt und praktisch windstill; azyklisch und daher wenig Leute auf Tour',
    },
    conditions: 'Kalt und praktisch windstill; azyklisch',
    notes: 'Solo tour; wenig Leute',
    rating: 4,
    createdAt: new Date('2026-02-01').getTime(),
  },
  {
    id: 'tour-1452',
    name: 'Stotzigen Firsten 2747m',
    date: '2026-02-07',
    participants: ['Jonas Widmer', 'Lukas Preiswerk', 'Niclas Genovese'],
    route: {
      name: 'Stotzigen Firsten 2747m',
      waypoints: [
        { lat: 46.5960, lon: 8.5070, label: 'Realp', elevation: 1538 },
        { lat: 46.5880, lon: 8.4950, label: 'Normalroute', elevation: 2200 },
        { lat: 46.5800, lon: 8.4850, label: 'Stotzigen Firsten', elevation: 2747 },
      ],
      dangerZones: [],
      totalElevation: 1250,
      distance: 10,
      estimatedTime: 'variable',
      difficulty: 'WS',
      keyInfo: 'Abfahrt via Nordhänge. Mittelmässig Volk; Nordabfahrt mit gutem Pulverschnee; nicht direkt vom Gipfel',
    },
    conditions: 'Mittelmässig Volk; Nordabfahrt mit gutem Pulverschnee',
    notes: 'Nordabfahrt mit gutem Pulver; nicht direkt vom Gipfel',
    rating: 5,
    createdAt: new Date('2026-02-07').getTime(),
  },
  {
    id: 'tour-1453',
    name: 'Balmer Grätli c. 2250m',
    date: '2026-02-15',
    participants: ['Jonas Widmer', 'Lukas Preiswerk'],
    route: {
      name: 'Balmer Grätli c. 2250m',
      waypoints: [
        { lat: 46.8700, lon: 8.5600, label: 'Pt. 1036m', elevation: 1036 },
        { lat: 46.8600, lon: 8.5500, label: 'Normalroute', elevation: 1700 },
        { lat: 46.8500, lon: 8.5400, label: 'Balmer Grätli', elevation: 2250 },
      ],
      dangerZones: [],
      totalElevation: 1250,
      distance: 10,
      estimatedTime: 'variable',
      difficulty: 'WS',
      keyInfo: 'Sehr wenig Betrieb vergleichsweise; super Pulverschnee; unten Schneelage knapp',
    },
    conditions: 'Super Pulverschnee; Schneelage unten knapp',
    notes: 'Sehr wenig Betrieb; super Pulver',
    rating: 5,
    createdAt: new Date('2026-02-15').getTime(),
  },
  {
    id: 'tour-1454',
    name: 'Arnialp',
    date: '2026-02-22',
    participants: ['Niclas Genovese', 'Laura Köcher'],
    route: {
      name: 'Arnialp',
      waypoints: [
        { lat: 46.8920, lon: 8.6350, label: 'Schönenboden', elevation: 1100 },
        { lat: 46.8850, lon: 8.6250, label: 'Mittlist Arni', elevation: 1500 },
        { lat: 46.8780, lon: 8.6150, label: 'Richtung Arnitriste', elevation: 1800 },
        { lat: 46.8800, lon: 8.6100, label: 'Richtung Wandelen', elevation: 1950 },
      ],
      dangerZones: [],
      totalElevation: 850,
      distance: 8,
      estimatedTime: 'variable',
      difficulty: 'WS',
      keyInfo: 'Feuchter Pulverschnee; kein Volk da Lawinenstufe 3+; keine Wummgeräusche; keine spontanen Anrisse oder Fernauslösungen',
    },
    conditions: 'Feuchter Pulverschnee; Lawinenstufe 3+; keine Wummgeräusche',
    notes: 'Kein Volk da Lawinenstufe 3+; keine spontanen Anrisse oder Fernauslösungen',
    rating: 4,
    createdAt: new Date('2026-02-22').getTime(),
  },
];
